<template><div><h1 id="유틸리티" tabindex="-1"><a class="header-anchor" href="#유틸리티"><span>유틸리티</span></a></h1>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> PivotUtilities <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue-pivottable'</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="numberformat" tabindex="-1"><a class="header-anchor" href="#numberformat"><span>numberFormat</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line">  <span class="token keyword">const</span> usFmt <span class="token operator">=</span> PivotUtilities<span class="token punctuation">.</span><span class="token function">numberFormat</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token keyword">const</span> usFmtInt <span class="token operator">=</span> PivotUtilities<span class="token punctuation">.</span><span class="token function">numberFormat</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">digitsAfterDecimal</span><span class="token operator">:</span> <span class="token number">0</span> <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token keyword">const</span> usFmtPct <span class="token operator">=</span> PivotUtilities<span class="token punctuation">.</span><span class="token function">numberFormat</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token literal-property property">digitsAfterDecimal</span><span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">scaler</span><span class="token operator">:</span> <span class="token number">100</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">suffix</span><span class="token operator">:</span> <span class="token string">'%'</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="sortas" tabindex="-1"><a class="header-anchor" href="#sortas"><span>sortAs</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> <span class="token function-variable function">sorters</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token string-property property">'Day of Week'</span><span class="token operator">:</span> PivotUtilities<span class="token punctuation">.</span><span class="token function">sortAs</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'Monday'</span><span class="token punctuation">,</span> <span class="token string">'Tuesday'</span><span class="token punctuation">,</span> <span class="token string">'Wednesday'</span><span class="token punctuation">,</span> <span class="token string">'Thursday'</span><span class="token punctuation">,</span> <span class="token string">'Friday'</span><span class="token punctuation">,</span> <span class="token string">'Saturday'</span><span class="token punctuation">,</span> <span class="token string">'Sunday'</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="aggregatortemplates" tabindex="-1"><a class="header-anchor" href="#aggregatortemplates"><span>aggregatorTemplates</span></a></h2>
<p>내장 집계기 및 집계기 템플릿</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> aggregators <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">tpl</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token string-property property">'Count'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span>usFmtInt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Count Unique Values'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">countUnique</span><span class="token punctuation">(</span>usFmtInt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'List Unique Values'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">listUnique</span><span class="token punctuation">(</span><span class="token string">', '</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">Sum</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Integer Sum'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span>usFmtInt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Average'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">average</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Median'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">median</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sample Variance'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">var</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sample Standard Deviation'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">stdev</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Minimum'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">min</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Maximum'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">max</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'First'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">first</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Last'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">last</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sum over Sum'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">sumOverSum</span><span class="token punctuation">(</span>usFmt<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sum as Fraction of Total'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'total'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sum as Fraction of Rows'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'row'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Sum as Fraction of Columns'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">sum</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'col'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Count as Fraction of Total'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'total'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Count as Fraction of Rows'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'row'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string-property property">'Count as Fraction of Columns'</span><span class="token operator">:</span> tpl<span class="token punctuation">.</span><span class="token function">fractionOf</span><span class="token punctuation">(</span>tpl<span class="token punctuation">.</span><span class="token function">count</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token string">'col'</span><span class="token punctuation">,</span> usFmtPct<span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token punctuation">(</span>PivotUtilities<span class="token punctuation">.</span>aggregatorTemplates<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="locales" tabindex="-1"><a class="header-anchor" href="#locales"><span>locales</span></a></h2>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token keyword">const</span> locales <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token literal-property property">en</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    aggregators<span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">localeStrings</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">renderError</span><span class="token operator">:</span> <span class="token string">'An error occurred rendering the PivotTable results.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">computeError</span><span class="token operator">:</span> <span class="token string">'An error occurred computing the PivotTable results.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">uiRenderError</span><span class="token operator">:</span> <span class="token string">'An error occurred rendering the PivotTable UI.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectAll</span><span class="token operator">:</span> <span class="token string">'Select All'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectNone</span><span class="token operator">:</span> <span class="token string">'Select None'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">tooMany</span><span class="token operator">:</span> <span class="token string">'(too many to list)'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">filterResults</span><span class="token operator">:</span> <span class="token string">'Filter values'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">totals</span><span class="token operator">:</span> <span class="token string">'Totals'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">vs</span><span class="token operator">:</span> <span class="token string">'vs'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">by</span><span class="token operator">:</span> <span class="token string">'by'</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token literal-property property">fr</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    frAggregators<span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">localeStrings</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">renderError</span><span class="token operator">:</span> <span class="token string">'Une erreur est survenue en dessinant le tableau croisé.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">computeError</span><span class="token operator">:</span> <span class="token string">'Une erreur est survenue en calculant le tableau croisé.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">uiRenderError</span><span class="token operator">:</span> <span class="token string">"Une erreur est survenue en dessinant l'interface du tableau croisé dynamique."</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectAll</span><span class="token operator">:</span> <span class="token string">'Sélectionner tout'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectNone</span><span class="token operator">:</span> <span class="token string">'Ne rien sélectionner'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">tooMany</span><span class="token operator">:</span> <span class="token string">'(trop de valeurs à afficher)'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">filterResults</span><span class="token operator">:</span> <span class="token string">'Filtrer les valeurs'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">totals</span><span class="token operator">:</span> <span class="token string">'Totaux'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">vs</span><span class="token operator">:</span> <span class="token string">'sur'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">by</span><span class="token operator">:</span> <span class="token string">'par'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">apply</span><span class="token operator">:</span> <span class="token string">'Appliquer'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">cancel</span><span class="token operator">:</span> <span class="token string">'Annuler'</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token literal-property property">ko</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">    aggregators<span class="token punctuation">,</span></span>
<span class="line">    <span class="token literal-property property">localeStrings</span><span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token literal-property property">renderError</span><span class="token operator">:</span> <span class="token string">'피벗 테이블 결과를 렌더링하는 중 오류가 발생했습니다.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">computeError</span><span class="token operator">:</span> <span class="token string">'피벗 테이블 결과를 계산하는 중 오류가 발생했습니다.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">uiRenderError</span><span class="token operator">:</span> <span class="token string">'피벗 테이블 UI를 렌더링하는 중 오류가 발생했습니다.'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectAll</span><span class="token operator">:</span> <span class="token string">'모두 선택'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">selectNone</span><span class="token operator">:</span> <span class="token string">'선택 안 함'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">tooMany</span><span class="token operator">:</span> <span class="token string">'(목록에 표시하기에 너무 많음)'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">filterResults</span><span class="token operator">:</span> <span class="token string">'값 필터링'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">totals</span><span class="token operator">:</span> <span class="token string">'합계'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">vs</span><span class="token operator">:</span> <span class="token string">'vs'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">by</span><span class="token operator">:</span> <span class="token string">'기준'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">apply</span><span class="token operator">:</span> <span class="token string">'적용'</span><span class="token punctuation">,</span></span>
<span class="line">      <span class="token literal-property property">cancel</span><span class="token operator">:</span> <span class="token string">'취소'</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


