name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@SoftwareAngelsDev"
      - name: Build and Publish
        run: |
          echo @lexacode:https://npm.pkg.github.com/SoftwareAngelsDev > .npmrc
          echo '//npm.pkg.github.com/SoftwareAngelsDev:_authToken=${NPM_TOKEN}' >> .npmrc
          npm install
          npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}